### ISSUE TITLE
RuntimeException with laravel-https

### ISSUE THREAD

**Issue by sagytt** [jeremykenedy/laravel-https#3]
Hey Jeremy
I just wanted you to know that there is an issue when trying to do composer update, so i'm getting this message

" Could not load package jeremykenedy/laravel-https in http://repo.packagist.org: [UnexpectedValueException] Could not parse version constraint ~5.*: Invalid version string "~5.*"  
"

**Comment by maxi032** [comment]
I also get this error.  I am using Laravel 7.20 

I am on Homestead 9.0.3 
Windows 10 Pro

**Comment by jeremykenedy** [comment]
You need to run

```
composer self-update
```

**Comment by sagytt** [comment]
> You need to run
> 
> ```
> composer self-update
> ```

Thank you that worked!

**Comment by stanley87** [comment]
having this issue too in aws beanstalk env while aws codebuild
